const TIC_TAC_TOE_BEGIN = 'TIC_TAC_TOE_BEGIN';
const TIC_TAC_TOE_END = 'TIC_TAC_TOE_END';
const TIC_TAC_TOE_PLAY = 'TIC_TAC_TOE_PLAY';

export {
  TIC_TAC_TOE_BEGIN,
  TIC_TAC_TOE_END,
  TIC_TAC_TOE_PLAY,
};
